version: "3"

services:
  todo-backend:
    container_name: todo-backend
    build:
      context: .
      dockerfile: ./apps/todo/backend/Dockerfile
    restart: always
    ports:
      - 443:443
    networks:
      - todo_network
  todo-frontend:
    container_name: todo-frontend
    build:
      context: .
      dockerfile: ./apps/todo/frontend/Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - todo_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  todo_network:
    external: true
